export const ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  AUTH_REGISTER: '/auth/register',
  PROFILE: '/profile',
  OWNER: '/owner',
  OWNER_MEDIA: '/owner/media',
  OWNER_MEDIA_NEW: '/owner/media/new',
  OWNER_MEDIA_DETAIL: '/owner/media/$mediaId',
  OWNER_MEDIA_EDIT: '/owner/media/$mediaId/edit',
  MODERATOR: '/moderator',
  MODERATOR_MEDIA: '/moderator/media',
  MODERATOR_ORDERS: '/moderator/orders',
  MODERATOR_USERS: '/moderator/users',
  MODERATOR_REJECTED: '/moderator/rejected',
  MODERATOR_SETTINGS: '/moderator/settings',
  MODERATOR_HELP: '/moderator/help',
} as const;
